In [1]:
'''
@author Bilal H. Hungund K.

ML Algorithm -  Gradient Descent
'''
from sklearn.preprocessing import scale
class GradientDescent:
 
    learning_rate = 0.01
    max_iter = 2000
    scale = False
    new_theta = []
    
    def __init__(self, learning_rate=0.01, max_iter=2000, scale=False):
        self.learning_rate = learning_rate
        self.max_iter = max_iter
        self.scale = scale
        
    def fit(self, X, y):
        ones = [1] * len(X)
        if self.scale:
            X = scale(X)
        X = np.transpose(np.concatenate((np.array([ones]).reshape(-1, 1), X), axis=1))
        zeroes = [0] * X.shape[0]
        theta = np.array([zeroes])
        for i in range(self.max_iter):
            htheta = np.dot(theta, X)
            diff_theta = htheta - y.values
            partial_derivative_theta = np.dot(diff_theta, np.transpose(X)) / len(y.values)
            theta = theta - self.learning_rate * partial_derivative_theta
            self.new_theta.append(theta)
    
    def predict(self, X):
        if scale:
            X = scale(X)
        theta0 = self.new_theta[self.max_iter-1][0][0]
        thetas = []
        for i in range(1, self.new_theta[self.max_iter-1].shape[1]):
            thetas.append(self.new_theta[self.max_iter-1][0][i])
        predict = theta0 + (thetas * X).sum(axis=1)
        return(predict)
    
    def score(self, X, y):
        if scale:
            X = scale(X)
        pred_y = self.predict(X)
        mean_y = y.mean()
        ess = sum((y - mean_y) ** 2)
        rss = sum((y - pred_y) ** 2)
        rsquared = 1 - (rss/ess)
        return rsquared

In [2]:
import pandas as pd
import numpy as np

advertising = pd.read_csv('Advertising.csv')
advertising = advertising.drop('No', axis=1)
advertising.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
X = advertising.drop('sales', axis=1)
y = advertising['sales']

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [5]:
from sklearn.linear_model import LinearRegression
from xgboost.sklearn import XGBRegressor
from sklearn.ensemble import RandomForestRegressor

In [6]:
regressor = GradientDescent(learning_rate=0.01, max_iter=5000, scale=True)
regressor.fit(x_train, y_train)
predict = regressor.predict(x_test)
print("Custom Model R-Squared: ", regressor.score(x_train, y_train))

clf = LinearRegression()
clf.fit(x_train, y_train)
predict_lin = clf.predict(x_test)
print("Built in R-Squared: ", clf.score(x_train, y_train))

dicts = {'Predicted_Custom_Model': np.round(predict, 2), 
         'Predicted_Builtin_Model': np.round(predict_lin,2), 
         'Actual_Data': y_test}
pd.DataFrame(dicts)

Custom Model R-Squared:  0.8935083778547789
Built in R-Squared:  0.8935083778547789

     Predicted_Custom_Model  Predicted_Builtin_Model  Actual_Data
117                    6.17                     6.61          9.4
65                     7.42                     7.87          9.3
18                     9.51                     9.97         11.3
87                    15.16                    15.61         16.0
139                   19.24                    19.65         20.7
27                    16.69                    17.07         15.9
105                   17.51                    17.94         19.2
72                     9.89                    10.37          8.8
194                   16.06                    16.48         17.3
152                   15.97                    16.37         16.6
62                    16.43                    16.81         15.7
155                    4.85                     5.34          3.2
145                    9.33                     9.74         10.3
39                    20.06                    20.44         21.5
51                     8.92                     9.36         10.7
3                     17.18                    17.61         18.5
113                   16.02                    16.41         15.9
184                   18.18                    18.55         17.6
146                   14.94                    15.32         13.2
88                    11.30                    11.75         12.9
69                    20.70                    21.09         22.3
183                   23.78                    24.14         26.2
41                    16.89                    17.30         17.1
33                    18.50                    18.87         17.4
50                    12.29                    12.68         11.4
137                   20.51                    20.87         20.8
158                    9.91                    10.40          7.3
54                    20.00                    20.37         20.2
64                    16.53                    16.97         18.0
114                   14.84                    15.30         14.6
174                   13.40                    13.78         11.5
10                     6.62                     7.07          8.6
132                    7.96                     8.45          5.7
2                     11.83                    12.32          9.3
46                     8.47                     8.92         10.6
192                    4.04                     4.52          5.9
187                   16.68                    17.08         17.3
165                   13.92                    14.29         11.9
4                     12.84                    13.24         12.9
59                    17.73                    18.13         18.4